services:
  node:
    image: node:26.5.0-alpine3.24
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    ports:
      - 5173:5173
    volumes:
      - .:/home/node
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./dist:/usr/share/nginx/html:ro

